### ISSUE TITLE
Are the kernels hosted at bazdara.com/arch/i686/ built from this repo?

### ISSUE THREAD

**Issue by parkerlreed** [Asus-T100/kernel#1]
Just curious if these were related. I've been following it closely and love all the work that is being put into it.

**Comment by pinkflozd** [comment]
Yes, the ARCH packages found on http://bazdara.com/arch/i686/ are built from this repo.
atm i'm not building x86_64 packages, but if someone wants them i can start building if the interested party will test them

currently:
linux-T100 = linux-4.3.x branch (most of the times stable)
linux-T100-bfs = linux-4.3.x-bfs branch (currently stable but can be unstable on some upgrades)
linux-T100-dev = linux-mainline (unstable, currently WIFI doesnt work)

you can also add it to pacman.conf to have auto updates:
[T100]
SigLevel = Optional TrustAll
Usage = All
Server = http://bazdara.com/arch/$arch

**Comment by parkerlreed** [comment]
Thanks.
