### ISSUE TITLE
Are the x86_64 kernels not being built anymore?

### ISSUE THREAD

**Issue by parkerlreed** [Asus-T100/kernel#4]
https://www.bazdara.com/arch/x86_64/

Noticed the folder was empty. Would love some x86_64 builds but I understand it requires more effort to support it. 

As an aside I'm not sure if you noticed yet but they broke byt-rt5640 in upstream. https://bugs.archlinux.org/task/48936

Not even working in linux-git. Really sad that the Bay Trail hardware is still so iffy in new kernels.

**Comment by parkerlreed** [comment]
Actually even just a PKGBUILD so I could package my own x86_64 would be great. I tried creating my own but don't have a base config to start with.

**Comment by pinkflozd** [comment]
i will get you a PKGBUILD and a i386 config... you can then start from there for 64bit...

for sound ... i have a TAF so i dont get any sound yet... intel devs working on it
but for the TA ... they switched the sound drivers on BYT ... there is a new SST driver that needs UCM files (https://github.com/plbossart/UCM/tree/master/bytcr-rt5640) 
did you tried with the new UCM files or just the asound.state file?

**Comment by parkerlreed** [comment]
Just the asound.state. I will try out the files, thanks.

**Comment by parkerlreed** [comment]
Do I need to remove the asound.state if using the UCM files?

**Comment by pinkflozd** [comment]
yes remove the asound.state and reboot

**Comment by parkerlreed** [comment]
Hmm so I removed the asound.state and everything shows up fine in pulseaudio (pavucontrol) but even with the output switched to headphones I am getting no audio. Device is showing up but not outputting. Will continue to look into this.

**Comment by parkerlreed** [comment]
Also it does seem to be generating its own /var/lib/alsa/asound.state on startup

**Comment by parkerlreed** [comment]
[dmesg.txt](https://github.com/Asus-T100/kernel/files/224173/dmesg.txt) (Fixed for the right dmesg file)

Here's the dmesg from Arch's 4.5.1 kernel in testing. UCM files definitely get picked up but no audio output.

EDIT: Also an interesting note: The old firmware files provided at https://github.com/T100Ubuntu/T100Ubuntu/wiki/Download-files do not work. I had to upgrade to testing/linux-firmware or else I got a ton of error messages in dmesg.

**Comment by pinkflozd** [comment]
you can maybe try https://github.com/plbossart/UCM/tree/stable/bytcr-rt5640 this HiFi from another branch ... 

btw https://github.com/Asus-T100/aur PKGBUILD + config
the config is really slimmed down ( a lot of useless stuff disabled maybe eaven some usefull stuff disabled)
you can use a default x64 config it should be just a couple of things to change in the first part of the config

currently the kernel uses a TAF touchscreen hack... you can use this revert patch ... 
https://github.com/Asus-T100/kernel/commit/74eeecf8303f69b4299ff2eb5acccfd91d9a6357.patch
save it in the aur folder

add it in PKGBUILD like so: 

  cd "kernel"

  patch -p1 -i "${srcdir}/74eeecf8303f69b4299ff2eb5acccfd91d9a6357.patch"

  if [ "${CARCH}" = "x86_64" ]; then
    cat "${srcdir}/config.x86_64" > ./.config
  else
    cat "${srcdir}/config" > ./.config
  fi

**Comment by parkerlreed** [comment]
Cheers. Will give this a shot.

**Comment by parkerlreed** [comment]
```
  CHK     include/generated/timeconst.h
  CC      kernel/bounds.s
kernel/bounds.c:1:0: error: code model ‘kernel’ not supported in the 32 bit mode
 /*
 ^
Kbuild:44: recipe for target 'kernel/bounds.s' failed
make[1]: *** [kernel/bounds.s] Error 1
make[1]: *** Waiting for unfinished jobs....
  UPD     include/generated/timeconst.h
Makefile:996: recipe for target 'prepare0' failed
make: *** [prepare0] Error 2
==> ERROR: A failure occurred in prepare().
    Aborting...
```

My modifications to the config for 64bit

```
CONFIG_64BIT=y
CONFIG_X86_64=y
CONFIG_X86=y
CONFIG_INSTRUCTION_DECODER=y
CONFIG_PERF_EVENTS_INTEL_UNCORE=y
CONFIG_OUTPUT_FORMAT="elf32-x86-64"
CONFIG_ARCH_DEFCONFIG="arch/x86/configs/x86_64_defconfig"
CONFIG_LOCKDEP_SUPPORT=y
CONFIG_STACKTRACE_SUPPORT=y
CONFIG_MMU=y
CONFIG_ARCH_MMAP_RND_BITS_MIN=28
CONFIG_ARCH_MMAP_RND_BITS_MAX=32
CONFIG_ARCH_MMAP_RND_COMPAT_BITS_MIN=8
CONFIG_ARCH_MMAP_RND_COMPAT_BITS_MAX=16
CONFIG_NEED_DMA_MAP_STATE=y
CONFIG_NEED_SG_DMA_LENGTH=y
CONFIG_GENERIC_ISA_DMA=y
CONFIG_GENERIC_BUG=y
CONFIG_GENERIC_HWEIGHT=y
CONFIG_ARCH_MAY_HAVE_PC_FDC=y
CONFIG_RWSEM_XCHGADD_ALGORITHM=y
CONFIG_GENERIC_CALIBRATE_DELAY=y
CONFIG_ARCH_HAS_CPU_RELAX=y
CONFIG_ARCH_HAS_CACHE_LINE_SIZE=y
CONFIG_HAVE_SETUP_PER_CPU_AREA=y
CONFIG_NEED_PER_CPU_EMBED_FIRST_CHUNK=y
CONFIG_NEED_PER_CPU_PAGE_FIRST_CHUNK=y
CONFIG_ARCH_HIBERNATION_POSSIBLE=y
CONFIG_ARCH_SUSPEND_POSSIBLE=y
CONFIG_ARCH_WANT_HUGE_PMD_SHARE=y
CONFIG_ARCH_WANT_GENERAL_HUGETLB=y
CONFIG_ARCH_SUPPORTS_OPTIMIZED_INLINING=y
CONFIG_ARCH_SUPPORTS_DEBUG_PAGEALLOC=y
CONFIG_HAVE_INTEL_TXT=y
CONFIG_ARCH_HWEIGHT_CFLAGS="-fcall-saved-ecx -fcall-saved-edx"
CONFIG_ARCH_SUPPORTS_UPROBES=y
CONFIG_FIX_EARLYCON_MEM=y
CONFIG_PGTABLE_LEVELS=2
CONFIG_DEFCONFIG_LIST="/lib/modules/$UNAME_RELEASE/.config"
CONFIG_IRQ_WORK=y
CONFIG_BUILDTIME_EXTABLE_SORT=y
```

EDIT: By the way for all the new config options that it presented I just hit enter for default.

**Comment by pinkflozd** [comment]
i think you need to change the option -m32 to -m64 in the Makefile ... sorry ... been optimizing it for 32bit
you can also try to sync the new options with:
https://liquorix.net/sources/4.5/config.amd64
i based my config on it (only 32bit version)

also change to: CONFIG_OUTPUT_FORMAT="elf64-x86-64"

be sure to make a pull request when you get a usable 64bit config... i can then keep the 64bit version in sync and build packages for it too ;)

**Comment by parkerlreed** [comment]
I'm tempted to just do a clean install of 32bit Arch :( I was trying to stick to x86_64 due to stubbornness but if the 32bit is what is being actively worked on and targeted then I can do that for the T100. Thanks again for all the help. Here's to hoping mainline will fully support us sometime in the future. :)
